//
//  elements_add.swift
//  PeriodicTable
//
//  Created by Alexander Meinecke on 28.09.18.
//  Copyright © 2018 Alexander Meinecke. All rights reserved.
//

import UIKit

extension Elemente_TableViewController {
    func createArray(sort: Int) -> [Element] {
        var createElements: [Element] = []
        
        let e1 = Element(name: "Wasserstoff", kurz: "H", gewicht: 1.0, en: 2.2, radioakt: nil, hgruppe: 1, ngruppe: nil, schale: 1, dichte: 0.08, schmelzpunkt: -259, siedepunkt: -252, oz: 1)
        let e2 = Element(name: "Helium", kurz: "He", gewicht: 4.0, en: nil, radioakt: nil, hgruppe: 8, ngruppe: nil, schale: 1, dichte: 0.17, schmelzpunkt: -272, siedepunkt: -269, oz: 2)
        let e3 = Element(name: "Lithium", kurz: "Li", gewicht: 6.9, en: 1, radioakt: nil, hgruppe: 1, ngruppe: nil, schale: 2, dichte: 0.53, schmelzpunkt: 181, siedepunkt: 1342, oz: 3)
        let e4 = Element(name: "Beryllium", kurz: "Be", gewicht: 9.0, en: 1.5, radioakt: nil, hgruppe: 2, ngruppe: nil, schale: 2, dichte: 1.85, schmelzpunkt: 1278, siedepunkt: 2970, oz: 4)
        let e5 = Element(name: "Bor", kurz: "B", gewicht: 10.8, en: 2.0, radioakt: nil, hgruppe: 3, ngruppe: nil, schale: 2, dichte: 2.34, schmelzpunkt: 2300, siedepunkt: 2550, oz: 5)
        let e6 = Element(name: "Kohlenstoff", kurz: "C", gewicht: 12.0, en: 2.5, radioakt: nil, hgruppe: 4, ngruppe: nil, schale: 2, dichte: 2.25, schmelzpunkt: 3650, siedepunkt: 4827, oz: 6)
        let e7 = Element(name: "Stickstoff", kurz: "N", gewicht: 14.0, en: 3.1, radioakt: nil, hgruppe: 5, ngruppe: nil, schale: 2, dichte: 1.17, schmelzpunkt: -210, siedepunkt: -196, oz: 7)
        let e8 = Element(name: "Sauerstoff", kurz: "O", gewicht: 16.0, en: 3.5, radioakt: nil, hgruppe: 6, ngruppe: nil, schale: 2, dichte: 1.33, schmelzpunkt: -219, siedepunkt: -183, oz: 8)
        let e9 = Element(name: "Flour", kurz: "F", gewicht: 19.0, en: 4.1, radioakt: nil, hgruppe: 7, ngruppe: nil, schale: 2, dichte: 1.58, schmelzpunkt: -219, siedepunkt: -188, oz: 9)
        let e10 = Element(name: "Neon", kurz: "Ne", gewicht: 20.2, en: nil, radioakt: nil, hgruppe: 8, ngruppe: nil, schale: 2, dichte: 0.84, schmelzpunkt: -249, siedepunkt: -246, oz: 10)
        let e11 = Element(name: "Natrium", kurz: "Na", gewicht: 23.0, en: 1.0, radioakt: nil, hgruppe: 1, ngruppe: nil, schale: 3, dichte: 0.97, schmelzpunkt: 98, siedepunkt: 883, oz: 11)
        let e12 = Element(name: "Magnesium", kurz: "Mg", gewicht: 24.3, en: 1.2, radioakt: nil, hgruppe: 2, ngruppe: nil, schale: 3, dichte: 1.74, schmelzpunkt: 649, siedepunkt: 1107, oz: 12)
        let e13 = Element(name: "Aluminium", kurz: "Al", gewicht: 27.0, en: 1.5, radioakt: nil, hgruppe: 3, ngruppe: nil, schale: 3, dichte: 2.7, schmelzpunkt: 660, siedepunkt: 2467, oz: 13)
        let e14 = Element(name: "Silicium", kurz: "Si", gewicht: 28.1, en: 1.7, radioakt: nil, hgruppe: 4, ngruppe: nil, schale: 3, dichte: 2.33, schmelzpunkt: 1410, siedepunkt: 2355, oz: 14)
        let e15 = Element(name: "Phosphor", kurz: "P", gewicht: 31.0, en: 2.1, radioakt: nil, hgruppe: 5, ngruppe: nil, schale: 3, dichte: 1.82, schmelzpunkt: 44, siedepunkt: 280, oz: 15)
        let e16 = Element(name: "Schwefel", kurz: "S", gewicht: 32.0, en: 2.4, radioakt: nil, hgruppe: 6, ngruppe: nil, schale: 3, dichte: 2.07, schmelzpunkt: 119, siedepunkt: 2831, oz: 16)
        let e17 = Element(name: "Chlor", kurz: "Cl", gewicht: 35.5, en: 2.8, radioakt: nil, hgruppe: 7, ngruppe: nil, schale: 3, dichte: 2.95, schmelzpunkt: -101, siedepunkt: -35, oz: 17)
        let e18 = Element(name: "Argon", kurz: "Ar", gewicht: 40.0, en: nil, radioakt: nil, hgruppe: 8, ngruppe: nil, schale: 3, dichte: 1.66, schmelzpunkt: -189, siedepunkt: -186, oz: 18)
        let e19 = Element(name: "Kalium", kurz: "K", gewicht: 39.0, en: 0.9, radioakt: nil, hgruppe: 1, ngruppe: nil, schale: 4, dichte: 0.86, schmelzpunkt: 63, siedepunkt: 760, oz: 19)
        let e20 = Element(name: "Calcium", kurz: "Ca", gewicht: 40.0, en: 1.0, radioakt: nil, hgruppe: 2, ngruppe: nil, schale: 4, dichte: 1.54, schmelzpunkt: 839, siedepunkt: 1484, oz: 20)
        let e21 = Element(name: "Scandium", kurz: "Sc", gewicht: 45.0, en: 1.2, radioakt: nil, hgruppe: nil, ngruppe: 1, schale: 4, dichte: 2.99, schmelzpunkt: 1539, siedepunkt: 2831, oz: 21)
        let e22 = Element(name: "Titan", kurz: "Ti", gewicht: 47.9, en: 1.3, radioakt: nil, hgruppe: nil, ngruppe: 2, schale: 4, dichte: 4.51, schmelzpunkt: 1660, siedepunkt: 3287, oz: 22)
        let e23 = Element(name: "Vanadium", kurz: "V", gewicht: 51.0, en: 1.5, radioakt: nil, hgruppe: nil, ngruppe: 3, schale: 4, dichte: 6.09, schmelzpunkt: 1890, siedepunkt: 3380, oz: 23)
        let e24 = Element(name: "Chrom", kurz: "Cr", gewicht: 52.0, en: 1.6, radioakt: nil, hgruppe: nil, ngruppe: 4, schale: 4, dichte: 7.14, schmelzpunkt: 1857, siedepunkt: 2672, oz: 24)
        let e25 = Element(name: "Mangan", kurz: "Mg", gewicht: 54.9, en: 1.6, radioakt: nil, hgruppe: nil, ngruppe: 5, schale: 4, dichte: 7.44, schmelzpunkt: 1244, siedepunkt: 1962, oz: 25)
        let e26 = Element(name: "Eisen", kurz: "Fe", gewicht: 55.8, en: 1.6, radioakt: nil, hgruppe: nil, ngruppe: 6, schale: 4, dichte: 7.87, schmelzpunkt: 1535, siedepunkt: 2750, oz: 26)
        let e27 = Element(name: "Kobalt", kurz: "Co", gewicht: 58.9, en: 1.7, radioakt: nil, hgruppe: nil, ngruppe: 7, schale: 4, dichte: 8.89, schmelzpunkt: 1495, siedepunkt: 2870, oz: 27)
        let e28 = Element(name: "Nickel", kurz: "Ni", gewicht: 58.7, en: 1.8, radioakt: nil, hgruppe: nil, ngruppe: 8, schale: 4, dichte: 8.91, schmelzpunkt: 1453, siedepunkt: 2730, oz: 28)
        let e29 = Element(name: "Kupfer", kurz: "Cu", gewicht: 63.5, en: 1.8, radioakt: nil, hgruppe: nil, ngruppe: 9, schale: 4, dichte: 8.91, schmelzpunkt: 1083, siedepunkt: 2567, oz: 29)
        let e30 = Element(name: "Zink", kurz: "Zn", gewicht: 65.4, en: 1.7, radioakt: nil, hgruppe: nil, ngruppe: 10, schale: 4, dichte: 7.14, schmelzpunkt: 420, siedepunkt: 907, oz: 30)
        let e31 = Element(name: "Gallium", kurz: "Ga", gewicht: 69.7, en: 1.8, radioakt: nil, hgruppe: 3, ngruppe: nil, schale: 4, dichte: 8.92, schmelzpunkt: 30, siedepunkt: 2403, oz: 31)
        let e32 = Element(name: "Germanium", kurz: "Ge", gewicht: 72.6, en: 2.0, radioakt: nil, hgruppe: 4, ngruppe: nil, schale: 4, dichte: 5.91, schmelzpunkt: 937, siedepunkt: 2830, oz: 32)
        let e33 = Element(name: "Arsen", kurz: "As", gewicht: 74.9, en: 2.2, radioakt: nil, hgruppe: 5, ngruppe: nil, schale: 4, dichte: 5.72, schmelzpunkt: 613, siedepunkt: 817, oz: 33)
        let e34 = Element(name: "Selen", kurz: "Se", gewicht: 79.0, en: 2.5, radioakt: nil, hgruppe: 6, ngruppe: nil, schale: 4, dichte: 4.81, schmelzpunkt: 217, siedepunkt: 685, oz: 34)
        let e35 = Element(name: "Brom", kurz: "Br", gewicht: 79.9, en: 2.7, radioakt: nil, hgruppe: 7, ngruppe: nil, schale: 4, dichte: 3.14, schmelzpunkt: -7, siedepunkt: 59, oz: 35)
        let e36 = Element(name: "Krypton", kurz: "Kr", gewicht: 83.8, en: nil, radioakt: nil, hgruppe: 8, ngruppe: nil, schale: 4, dichte: 3.48, schmelzpunkt: -157, siedepunkt: -252, oz: 36)
        let e37 = Element(name: "Rubidium", kurz: "Rb", gewicht: 85.5, en: 0.9, radioakt: nil, hgruppe: 1, ngruppe: nil, schale: 5, dichte: 1.53, schmelzpunkt: 39, siedepunkt: 686, oz: 37)
        let e38 = Element(name: "Strontium", kurz: "Sr", gewicht: 87.6, en: 1.0, radioakt: nil, hgruppe: 2, ngruppe: nil, schale: 5, dichte: 2.63, schmelzpunkt: 769, siedepunkt: 1384, oz: 38)
        let e39 = Element(name: "Yttrium", kurz: "Y", gewicht: 88.9, en: 1.1, radioakt: nil, hgruppe: nil, ngruppe: 1, schale: 5, dichte: 4.47, schmelzpunkt: 1523, siedepunkt: 3338, oz: 39)
        let e40 = Element(name: "Zirconium", kurz: "Zr", gewicht: 91.2, en: 1.2, radioakt: nil, hgruppe: nil, ngruppe: 2, schale: 5, dichte: 6.51, schmelzpunkt: 1852, siedepunkt: 4377, oz: 40)
        let e41 = Element(name: "Niob", kurz: "Nb", gewicht: 92.9, en: 1.2, radioakt: nil, hgruppe: nil, ngruppe: 3, schale: 5, dichte: 8.58, schmelzpunkt: 2468, siedepunkt: 4742, oz: 41)
        let e42 = Element(name: "Molybdän", kurz: "Mo", gewicht: 95.9, en: 1.3, radioakt: nil, hgruppe: nil, ngruppe: 4, schale: 5, dichte: 10.3, schmelzpunkt: 2617, siedepunkt: 5560, oz: 42)
        let e43 = Element(name: "Technetium", kurz: "Tc", gewicht: 98.9, en: 1.4, radioakt: nil, hgruppe: nil, ngruppe: 5, schale: 5, dichte: 11.5, schmelzpunkt: 2172, siedepunkt: 4877, oz: 43)
        let e44 = Element(name: "Ruthenium", kurz: "Ru", gewicht: 101.1, en: 1.4, radioakt: nil, hgruppe: nil, ngruppe: 6, schale: 5, dichte: 12.5, schmelzpunkt: 2310, siedepunkt: 3900, oz: 44)
        let e45 = Element(name: "Rhodium", kurz: "Rh", gewicht: 102.9, en: 1.4, radioakt: nil, hgruppe: nil, ngruppe: 7, schale: 5, dichte: 12.4, schmelzpunkt: 1966, siedepunkt: 5627, oz: 45)
        let e46 = Element(name: "Palladium", kurz: "Pd", gewicht: 106.42, en: 1.4, radioakt: nil, hgruppe: nil, ngruppe: 8, schale: 5, dichte: 12.0, schmelzpunkt: 1554, siedepunkt: 2970, oz: 46)
        let e47 = Element(name: "Silber", kurz: "Ag", gewicht: 107.9, en: 1.4, radioakt: nil, hgruppe: nil, ngruppe: 9, schale: 5, dichte: 10.5, schmelzpunkt: 962, siedepunkt: 2212, oz: 47)
        let e48 = Element(name: "Cadmium", kurz: "Cd", gewicht: 112.4, en: 1.5, radioakt: nil, hgruppe: nil, ngruppe: 10, schale: 5, dichte: 8.64, schmelzpunkt: 321, siedepunkt: 765, oz: 48)
        let e49 = Element(name: "Indium", kurz: "In", gewicht: 114.8, en: 1.5, radioakt: nil, hgruppe: 3, ngruppe: nil, schale: 5, dichte: 7.31, schmelzpunkt: 157, siedepunkt: 2080, oz: 49)
        let e50 = Element(name: "Zinn", kurz: "Sn", gewicht: 118.7, en: 1.7, radioakt: nil, hgruppe: 4, ngruppe: nil, schale: 5, dichte: 7.29, schmelzpunkt: 232, siedepunkt: 2270, oz: 50)
        let e51 = Element(name: "Antimon", kurz: "Sb", gewicht: 121.8, en: 1.7, radioakt: nil, hgruppe: 5, ngruppe: nil, schale: 5, dichte: 6.69, schmelzpunkt: 631, siedepunkt: 1750, oz: 51)
        let e52 = Element(name: "Tellur", kurz: "Te", gewicht: 127.6, en: 2.0, radioakt: nil, hgruppe: 6, ngruppe: nil, schale: 5, dichte: 5.25, schmelzpunkt: 450, siedepunkt: 990, oz: 52)
        let e53 = Element(name: "Iod", kurz: "I", gewicht: 126.9, en: 2.2, radioakt: nil, hgruppe: 7, ngruppe: nil, schale: 5, dichte: 4.94, schmelzpunkt: 114, siedepunkt: 184, oz: 53)
        let e54 = Element(name: "Xenon", kurz: "Xe", gewicht: 131.3, en: nil, radioakt: nil, hgruppe: 8, ngruppe: nil, schale: 5, dichte: 5.49, schmelzpunkt: -112, siedepunkt: -107, oz: 54)
        let e55 = Element(name: "Cäsium", kurz: "Cs", gewicht: 132.9, en: 0.9, radioakt: nil, hgruppe: 1, ngruppe: nil, schale: 6, dichte: 1.88, schmelzpunkt: 28, siedepunkt: 669, oz: 55)
        let e56 = Element(name: "Barium", kurz: "Ba", gewicht: 137.3, en: 1.0, radioakt: nil, hgruppe: 2, ngruppe: nil, schale: 6, dichte: 3.65, schmelzpunkt: 725, siedepunkt: 1640, oz: 56)
        let e57 = Element(name: "Lanthan", kurz: "La", gewicht: 138.9, en: 1.1, radioakt: nil, hgruppe: nil, ngruppe: 1, schale: 6, dichte: 6.16, schmelzpunkt: 920, siedepunkt: 3457, oz: 57)
        let e58 = Element(name: "Cer", kurz: "Ce", gewicht: 140.1, en: 1.1, radioakt: nil, hgruppe: nil, ngruppe: 1, schale: 6, dichte: 6.77, schmelzpunkt: 798, siedepunkt: 3257, oz: 58)
        let e59 = Element(name: "Praseodym", kurz: "Pr", gewicht: 140.9, en: 1.1, radioakt: nil, hgruppe: nil, ngruppe: 1, schale: 6, dichte: 6.48, schmelzpunkt: 931, siedepunkt: 3212, oz: 59)
        let e60 = Element(name: "Neodym", kurz: "Nd", gewicht: 144.2, en: 1.1, radioakt: nil, hgruppe: nil, ngruppe: 1, schale: 6, dichte: 7.0, schmelzpunkt: 1010, siedepunkt: 3127, oz: 60)
        let e61 = Element(name: "Promethium", kurz: "Pm", gewicht: 145.0, en: 1.1, radioakt: "17.7 a", hgruppe: nil, ngruppe: 1, schale: 6, dichte: 7.22, schmelzpunkt: 1080, siedepunkt: 2730, oz: 61)
        let e62 = Element(name: "Samarium", kurz: "Sm", gewicht: 150.4, en: 1.1, radioakt: nil, hgruppe: nil, ngruppe: 1, schale: 6, dichte: 7.54, schmelzpunkt: 1072, siedepunkt: 1778, oz: 62)
        let e63 = Element(name: "Europium", kurz: "Eu", gewicht: 152.0, en: 1.0, radioakt: nil, hgruppe: nil, ngruppe: 1, schale: 6, dichte: 5.25, schmelzpunkt: 822, siedepunkt: 1597, oz: 63)
        let e64 = Element(name: "Gadolinium", kurz: "Gd", gewicht: 157.3, en: 1.1, radioakt: nil, hgruppe: nil, ngruppe: 1, schale: 6, dichte: 7.89, schmelzpunkt: 1311, siedepunkt: 3233, oz: 64)
        let e65 = Element(name: "Terbium", kurz: "Tb", gewicht: 158.9, en: 1.1, radioakt: nil, hgruppe: nil, ngruppe: 1, schale: 6, dichte: 8.25, schmelzpunkt: 1360, siedepunkt: 3041, oz: 65)
        let e66 = Element(name: "Dysprosium", kurz: "Dy", gewicht: 162.5, en: 1.1, radioakt: nil, hgruppe: nil, ngruppe: 1, schale: 6, dichte: 8.56, schmelzpunkt: 1409, siedepunkt: 2335, oz: 66)
        let e67 = Element(name: "Holmium", kurz: "Ho", gewicht: 164.9, en: 1.1, radioakt: nil, hgruppe: nil, ngruppe: 1, schale: 6, dichte: 8.78, schmelzpunkt: 1470, siedepunkt: 2720, oz: 67)
        let e68 = Element(name: "Erbium", kurz: "Er", gewicht: 167.3, en: 1.1, radioakt: nil, hgruppe: nil, ngruppe: 1, schale: 6, dichte: 9.05, schmelzpunkt: 1522, siedepunkt: 2510, oz: 68)
        let e69 = Element(name: "Thulium", kurz: "Tm", gewicht: 168.9, en: 1.1, radioakt: nil, hgruppe: nil, ngruppe: 1, schale: 6, dichte: 9.32, schmelzpunkt: 1545, siedepunkt: 1727, oz: 69)
        let e70 = Element(name: "Ytterbium", kurz: "Yb", gewicht: 173.0, en: 1.1, radioakt: nil, hgruppe: nil, ngruppe: 1, schale: 6, dichte: 6.97, schmelzpunkt: 824, siedepunkt: 1193, oz: 70)
        let e71 = Element(name: "Lutetium", kurz: "Lu", gewicht: 175.0, en: 1.1, radioakt: nil, hgruppe: nil, ngruppe: 1, schale: 6, dichte: 9.84, schmelzpunkt: 1656, siedepunkt: 3410, oz: 71)
        let e72 = Element(name: "Hafnium", kurz: "Hf", gewicht: 178.5, en: 1.2, radioakt: nil, hgruppe: nil, ngruppe: 2, schale: 6, dichte: 13.3, schmelzpunkt: 2227, siedepunkt: 4602, oz: 72)
        let e73 = Element(name: "Tantal", kurz: "Ta", gewicht: 180.9, en: 1.3, radioakt: nil, hgruppe: nil, ngruppe: 3, schale: 6, dichte: 16.7, schmelzpunkt: 2996, siedepunkt: 5425, oz: 73)
        let e74 = Element(name: "Wolfram", kurz: "W", gewicht: 183.84, en: 1.4, radioakt: nil, hgruppe: nil, ngruppe: 4, schale: 6, dichte: 19.3, schmelzpunkt: 3407, siedepunkt: 5927, oz: 74)
        let e75 = Element(name: "Rhenium", kurz: "Re", gewicht: 186.2, en: 1.5, radioakt: nil, hgruppe: nil, ngruppe: 5, schale: 6, dichte: 21.0, schmelzpunkt: 3180, siedepunkt: 5627, oz: 75)
        let e76 = Element(name: "Osmium", kurz: "Os", gewicht: 190.2, en: 1.5, radioakt: nil, hgruppe: nil, ngruppe: 6, schale: 6, dichte: 22.6, schmelzpunkt: 2045, siedepunkt: 5027, oz: 76)
        let e77 = Element(name: "Iridium", kurz: "Ir", gewicht: 192.2, en: 1.6, radioakt: nil, hgruppe: nil, ngruppe: 7, schale: 6, dichte: 22.7, schmelzpunkt: 2410, siedepunkt: 4130, oz: 77)
        let e78 = Element(name: "Platin", kurz: "Pt", gewicht: 195.1, en: 1.4, radioakt: nil, hgruppe: nil, ngruppe: 8, schale: 6, dichte: 21.5, schmelzpunkt: 1772, siedepunkt: 3827, oz: 78)
        let e79 = Element(name: "Gold", kurz: "Au", gewicht: 197.0, en: 1.4, radioakt: nil, hgruppe: nil, ngruppe: 9, schale: 6, dichte: 19.3, schmelzpunkt: 1064, siedepunkt: 3080, oz: 79)
        let e80 = Element(name: "Quecksilber", kurz: "Hg", gewicht: 200.6, en: 1.5, radioakt: nil, hgruppe: nil, ngruppe: 10, schale: 6, dichte: 13.6, schmelzpunkt: -39, siedepunkt: 357, oz: 80)
        let e81 = Element(name: "Thallium", kurz: "Tl", gewicht: 204.4, en: 1.4, radioakt: nil, hgruppe: 3, ngruppe: nil, schale: 6, dichte: 11.9, schmelzpunkt: 304, siedepunkt: 1457, oz: 81)
        let e82 = Element(name: "Blei", kurz: "Pb", gewicht: 207.2, en: 1.6, radioakt: nil, hgruppe: 4, ngruppe: nil, schale: 6, dichte: 11.3, schmelzpunkt: 328, siedepunkt: -1740, oz: 82)
        let e83 = Element(name: "Bismut", kurz: "Bi", gewicht: 209.0, en: 1.7, radioakt: "10^19 a", hgruppe: 5, ngruppe: nil, schale: 6, dichte: 9.8, schmelzpunkt: 271, siedepunkt: 1560, oz: 83)
        let e84 = Element(name: "Polonium", kurz: "Po", gewicht: 209.0, en: 1.8, radioakt: "102 a", hgruppe: 6, ngruppe: nil, schale: 6, dichte: 9.2, schmelzpunkt: 254, siedepunkt: 962, oz: 84)
        let e85 = Element(name: "Astat", kurz: "At", gewicht: 210.0, en: 2.2, radioakt: "8.1 h", hgruppe: 7, ngruppe: nil, schale: 6, dichte: 8.75, schmelzpunkt: 302, siedepunkt: 337, oz: 85)
        let e86 = Element(name: "Radon", kurz: "Rn", gewicht: 222.0, en: nil, radioakt: "3.8 d", hgruppe: 8, ngruppe: nil, schale: 6, dichte: 9.23, schmelzpunkt: -71, siedepunkt: -62, oz: 86)
        let e87 = Element(name: "Francium", kurz: "Fr", gewicht: 223.0, en: 0.9, radioakt: "22 min", hgruppe: 1, ngruppe: nil, schale: 7, dichte: 1.9, schmelzpunkt: 27, siedepunkt: 677, oz: 87)
        let e88 = Element(name: "Radium", kurz: "Ra", gewicht: 226.0, en: 1.0, radioakt: "1600 a", hgruppe: 2, ngruppe: nil, schale: 7, dichte: 5.5, schmelzpunkt: 700, siedepunkt: 1140, oz: 88)
        let e89 = Element(name: "Actinium", kurz: "Ac", gewicht: 227.0, en: 1.0, radioakt: "22 a", hgruppe: nil, ngruppe: 1, schale: 7, dichte: 10.1, schmelzpunkt: 1050, siedepunkt: 3200, oz: 89)
        let e90 = Element(name: "Thorium", kurz: "Th", gewicht: 232.0, en: 1.1, radioakt: "1.4 * 10^10 a", hgruppe: nil, ngruppe: 1, schale: 7, dichte: 11.7, schmelzpunkt: 1750, siedepunkt: 4790, oz: 90)
        let e91 = Element(name: "Protactinium", kurz: "Pa", gewicht: 231.0, en: 1.1, radioakt: "3.3 * 10^4 a", hgruppe: nil, ngruppe: 1, schale: 7, dichte: 15.4, schmelzpunkt: 1554, siedepunkt: 4030, oz: 91)
        let e92 = Element(name: "Uran", kurz: "U", gewicht: 238.0, en: 1.2, radioakt: "4.5 * 10^9 a", hgruppe: nil, ngruppe: 1, schale: 7, dichte: 19.0, schmelzpunkt: 1132, siedepunkt: 3818, oz: 92)
        let e93 = Element(name: "Neptunium", kurz: "Np", gewicht: 237.0, en: 1.2, radioakt: "2.1 * 10^6 a", hgruppe: nil, ngruppe: 1, schale: 7, dichte: 20.5, schmelzpunkt: 640, siedepunkt: 3902, oz: 93)
        let e94 = Element(name: "Plutonium", kurz: "Pu", gewicht: 244.0, en: 1.2, radioakt: "8.0 * 10^7 a", hgruppe: nil, ngruppe: 1, schale: 7, dichte: 19.7, schmelzpunkt: 641, siedepunkt: 3327, oz: 94)
        let e95 = Element(name: "Americium", kurz: "Am", gewicht: 243.0, en: 1.2, radioakt: "7370 a", hgruppe: nil, ngruppe: 1, schale: 7, dichte: 13.7, schmelzpunkt: 994, siedepunkt: 2607, oz: 95)
        let e96 = Element(name: "Curium", kurz: "Cm", gewicht: 247.0, en: 1.2, radioakt: "1.6 * 10^7 a", hgruppe: nil, ngruppe: 1, schale: 7, dichte: 13.5, schmelzpunkt: 1340, siedepunkt: 3110, oz: 96)
        let e97 = Element(name: "Berkelium", kurz: "Bk", gewicht: 247.0, en: 1.2, radioakt: "1400 a", hgruppe: nil, ngruppe: 1, schale: 7, dichte: 13.3, schmelzpunkt: 986, siedepunkt: nil, oz: 97)
        let e98 = Element(name: "Californium", kurz: "Cf", gewicht: 247.0, en: 1.2, radioakt: "900 a", hgruppe: nil, ngruppe: 1, schale: 7, dichte: 15.1, schmelzpunkt: 900, siedepunkt: nil, oz: 98)
        let e99 = Element(name: "Einsteinium", kurz: "Es", gewicht: 247.0, en: 1.2, radioakt: "472 d", hgruppe: nil, ngruppe: 1, schale: 7, dichte: nil, schmelzpunkt: nil, siedepunkt: nil, oz: 99)
        let e100 = Element(name: "Fermium", kurz: "Fm", gewicht: 257.0, en: 1.2, radioakt: "101 d", hgruppe: nil, ngruppe: 1, schale: 7, dichte: nil, schmelzpunkt: nil, siedepunkt: nil, oz: 100)
        let e101 = Element(name: "Mendelevium", kurz: "Md", gewicht: 259.0, en: 1.2, radioakt: "52 d", hgruppe: nil, ngruppe: 1, schale: 7, dichte: nil, schmelzpunkt: nil, siedepunkt: nil, oz: 101)
        let e102 = Element(name: "Nobelium", kurz: "No", gewicht: 258.0, en: 1.2, radioakt: "58 min", hgruppe: nil, ngruppe: 1, schale: 7, dichte: nil, schmelzpunkt: nil, siedepunkt: nil, oz: 102)
        let e103 = Element(name: "Lawrencium", kurz: "Lr", gewicht: 264.0, en: 1.2, radioakt: "10 d", hgruppe: nil, ngruppe: 1, schale: 7, dichte: nil, schmelzpunkt: 1627, siedepunkt: nil, oz: 103)
        let e104 = Element(name: "Rutherfordium", kurz: "Rf", gewicht: 265.0, en: nil, radioakt: "13 h", hgruppe: nil, ngruppe: 2, schale: 7, dichte: nil, schmelzpunkt: nil, siedepunkt: nil, oz: 104)
        let e105 = Element(name: "Dubnium", kurz: "Db", gewicht: 268.0, en: nil, radioakt: "32 h", hgruppe: nil, ngruppe: 3, schale: 7, dichte: nil, schmelzpunkt: nil, siedepunkt: nil, oz: 105)
        let e106 = Element(name: "Seaborgium", kurz: "Sg", gewicht: 272.0, en: nil, radioakt: "1 h", hgruppe: nil, ngruppe: 4, schale: 7, dichte: nil, schmelzpunkt: nil, siedepunkt: nil, oz: 106)
        let e107 = Element(name: "Bohrium", kurz: "Bh", gewicht: 273.0, en: nil, radioakt: "90 min", hgruppe: nil, ngruppe: 5, schale: 7, dichte: nil, schmelzpunkt: nil, siedepunkt: nil, oz: 107)
        let e108 = Element(name: "Hassium", kurz: "Hs", gewicht: 276.0, en: nil, radioakt: "1 h", hgruppe: nil, ngruppe: 6, schale: 7, dichte: nil, schmelzpunkt: nil, siedepunkt: nil, oz: 108)
        let e109 = Element(name: "Meitnerium", kurz: "Mt", gewicht: 279.0, en: nil, radioakt: "6 min", hgruppe: nil, ngruppe: 7, schale: 7, dichte: nil, schmelzpunkt: nil, siedepunkt: nil, oz: 109)
        let e110 = Element(name: "Darmstadtium", kurz: "Ds", gewicht: 278.0, en: nil, radioakt: "10 s", hgruppe: nil, ngruppe: 8, schale: 7, dichte: nil, schmelzpunkt: nil, siedepunkt: nil, oz: 110)
        let e111 = Element(name: "Roentgenium", kurz: "Rg", gewicht: 283.0, en: nil, radioakt: "10 min", hgruppe: nil, ngruppe: 9, schale: 7, dichte: nil, schmelzpunkt: nil, siedepunkt: nil, oz: 111)
        let e112 = Element(name: "Copernicium", kurz: "Cn", gewicht: 285.0, en: nil, radioakt: "34 s", hgruppe: nil, ngruppe: 10, schale: 7, dichte: nil, schmelzpunkt: nil, siedepunkt: nil, oz: 112)
        let e113 = Element(name: "Nihonium", kurz: "Nh", gewicht: 286.0, en: nil, radioakt: nil, hgruppe: 3, ngruppe: nil, schale: 7, dichte: nil, schmelzpunkt: nil, siedepunkt: nil, oz: 113)
        let e114 = Element(name: "Flerovium", kurz: "Fl", gewicht: 289.0, en: nil, radioakt: nil, hgruppe: 4, ngruppe: nil, schale: 7, dichte: nil, schmelzpunkt: nil, siedepunkt: nil, oz: 114)
        let e115 = Element(name: "Moscovium", kurz: "Mc", gewicht: 288.0, en: nil, radioakt: nil, hgruppe: 5, ngruppe: nil, schale: 7, dichte: nil, schmelzpunkt: nil, siedepunkt: nil, oz: 115)
        let e116 = Element(name: "Livermorium", kurz: "Lv", gewicht: 293.0, en: nil, radioakt: nil, hgruppe: 6, ngruppe: nil, schale: 7, dichte: nil, schmelzpunkt: nil, siedepunkt: nil, oz: 116)
        let e117 = Element(name: "Tennessine", kurz: "Ts", gewicht: 294.0, en: nil, radioakt: nil, hgruppe: 7, ngruppe: nil, schale: 7, dichte: nil, schmelzpunkt: nil, siedepunkt: nil, oz: 117)
        let e118 = Element(name: "Oganesson", kurz: "Og", gewicht: 294.0, en: nil, radioakt: nil, hgruppe: 8, ngruppe: nil, schale: 7, dichte: nil, schmelzpunkt: nil, siedepunkt: nil, oz: 118)
        
        createElements.append(e1)
        createElements.append(e2)
        createElements.append(e3)
        createElements.append(e4)
        createElements.append(e5)
        createElements.append(e6)
        createElements.append(e7)
        createElements.append(e8)
        createElements.append(e9)
        createElements.append(e10)
        createElements.append(e11)
        createElements.append(e12)
        createElements.append(e13)
        createElements.append(e14)
        createElements.append(e15)
        createElements.append(e16)
        createElements.append(e17)
        createElements.append(e18)
        createElements.append(e19)
        createElements.append(e20)
        createElements.append(e21)
        createElements.append(e22)
        createElements.append(e23)
        createElements.append(e24)
        createElements.append(e25)
        createElements.append(e26)
        createElements.append(e27)
        createElements.append(e28)
        createElements.append(e29)
        createElements.append(e30)
        createElements.append(e31)
        createElements.append(e32)
        createElements.append(e33)
        createElements.append(e34)
        createElements.append(e35)
        createElements.append(e36)
        createElements.append(e37)
        createElements.append(e38)
        createElements.append(e39)
        createElements.append(e40)
        createElements.append(e41)
        createElements.append(e42)
        createElements.append(e43)
        createElements.append(e44)
        createElements.append(e45)
        createElements.append(e46)
        createElements.append(e47)
        createElements.append(e48)
        createElements.append(e49)
        createElements.append(e50)
        createElements.append(e51)
        createElements.append(e52)
        createElements.append(e53)
        createElements.append(e54)
        createElements.append(e55)
        createElements.append(e56)
        createElements.append(e57)
        createElements.append(e58)
        createElements.append(e59)
        createElements.append(e60)
        createElements.append(e61)
        createElements.append(e62)
        createElements.append(e63)
        createElements.append(e64)
        createElements.append(e65)
        createElements.append(e66)
        createElements.append(e67)
        createElements.append(e68)
        createElements.append(e69)
        createElements.append(e70)
        createElements.append(e71)
        createElements.append(e72)
        createElements.append(e73)
        createElements.append(e74)
        createElements.append(e75)
        createElements.append(e76)
        createElements.append(e77)
        createElements.append(e78)
        createElements.append(e79)
        createElements.append(e80)
        createElements.append(e81)
        createElements.append(e82)
        createElements.append(e83)
        createElements.append(e84)
        createElements.append(e85)
        createElements.append(e86)
        createElements.append(e87)
        createElements.append(e88)
        createElements.append(e89)
        createElements.append(e90)
        createElements.append(e91)
        createElements.append(e92)
        createElements.append(e93)
        createElements.append(e94)
        createElements.append(e95)
        createElements.append(e96)
        createElements.append(e97)
        createElements.append(e98)
        createElements.append(e99)
        createElements.append(e100)
        createElements.append(e101)
        createElements.append(e102)
        createElements.append(e103)
        createElements.append(e104)
        createElements.append(e105)
        createElements.append(e106)
        createElements.append(e107)
        createElements.append(e108)
        createElements.append(e109)
        createElements.append(e110)
        createElements.append(e111)
        createElements.append(e112)
        createElements.append(e113)
        createElements.append(e114)
        createElements.append(e115)
        createElements.append(e116)
        createElements.append(e117)
        createElements.append(e118)
        
        if sort == 2 {
            createElements = createElements.sorted(by: { $0.name < $1.name})
        } else if sort == 3 {
            createElements = createElements.sorted(by: { $0.gewicht > $1.gewicht})
        } else if sort == 1 {
        }
        
        return createElements
    }
}

func  checkNil() {
    if UserDefaults.standard.value(forKey: "text") == nil {
        UserDefaults.standard.set(false, forKey: "text")
    }
    
    if UserDefaults.standard.value(forKey: "filter") == nil {
        UserDefaults.standard.set("nichts", forKey: "filter")
    }
}



func checkSort() {
    if UserDefaults.standard.value(forKey: "sort") == nil {
        UserDefaults.standard.set(1, forKey: "sort")
    }
}
    

